services:
  _defaults:
    autowire: true
    autoconfigure: true
  Whs\Score\:
    resource: ../src/
  Symfony\Component\Serializer\Normalizer\CustomNormalizer:
    tags:
    - name: serializer.normalizer
      priority: 100